[package]
name = "task-group"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
futures-util = "0.3.28"
parking_lot = "0.12.1"
rand = "0.8.5"
tokio = { version = "1.29.1", features = ["rt"] }
